spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8090

# 주식 공공데이터 (금융위원회_주식시세정보)
krx:
  api:
    key: 6e44ea19e426d0313e5d161b2344d93d98636c7c0fbbb44285b4b3dc4929b136
    url: https://apis.data.go.kr/1160100/service/GetStockSecuritiesInfoService/getStockPriceInfo

# OPEN DART (금융감독원 전자공시)
dart:
  api:
    key: 5a032f1415547f59165ec30de69ff15eee107ed4
    url: https://opendart.fss.or.kr/api
