plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.14'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {

	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'

	// RESTCONTROLLER
	implementation 'com.fasterxml.jackson.core:jackson-databind'
	implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
	implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml'

	// JSONOBJECT
	implementation 'com.googlecode.json-simple:json-simple:1.1.1'

	// JAVA MAIL
	implementation 'org.springframework.boot:spring-boot-starter-mail'

	// VALIDATION
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// THYMELEAF
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

	// SPRING STARTER MODULE
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// MYSQL CONNECTOR JAVA
	runtimeOnly 'com.mysql:mysql-connector-j'

	// JDBC API
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'



	// DEVTOOLS
	implementation 'org.springframework.boot:spring-boot-devtools'

	// SPRINGBOOT TEST
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	// JUNIT
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
	implementation "org.jetbrains.kotlin:kotlin-stdlib"


}

tasks.named('test') {
	useJUnitPlatform()
}
